POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Individual Event",
  "details": null,
  "maximumAttendees": 1
}

###

POST http://localhost:3333/events/216809a8-af5f-47c5-b842-5d31f7ac5a21/attendees
Content-Type: application/json

{
  "name": "John Doe",
  "email": "jd@test.com"
}
