# Fetches all event records
POST http://localhost:3333/events
Content-Type: application/json

{
  "title": "Global Event",
  "details": "global summit",
  "maximumAttendees": 100
}

###

# Registers the user for an event
POST http://localhost:3333/events/d4b915fa-72d4-44a6-9e8f-936c58741b8e/attendees
Content-Type: application/json

{
  "name": "John Doe",
  "email": "jd23@test.com"
}

###

# Fetch a specific event
GET http://localhost:3333/events/591c3104-afa5-4ed1-bf53-64a90e59d127

###

#Fetch attendee event badge
GET http://localhost:3333/attendees/7/badge

